In [72]:
import numpy as np

In [73]:
x = np.random.random((5,5))

In [74]:
print x

[[ 0.29644828  0.83034798  0.65109818  0.93916215  0.35763547]
 [ 0.23920744  0.32780305  0.07036492  0.12180972  0.5984803 ]
 [ 0.06660388  0.80362676  0.20993676  0.95551542  0.36342028]
 [ 0.66033918  0.28771308  0.46057647  0.98165272  0.60108776]
 [ 0.19503242  0.11069177  0.41422103  0.58119139  0.24639779]]


In [75]:
t = x[0:0+2*2:2,:]

In [76]:
print t

[[ 0.29644828  0.83034798  0.65109818  0.93916215  0.35763547]
 [ 0.06660388  0.80362676  0.20993676  0.95551542  0.36342028]]


In [77]:
u = x[0:4,:]
print u

[[ 0.29644828  0.83034798  0.65109818  0.93916215  0.35763547]
 [ 0.23920744  0.32780305  0.07036492  0.12180972  0.5984803 ]
 [ 0.06660388  0.80362676  0.20993676  0.95551542  0.36342028]
 [ 0.66033918  0.28771308  0.46057647  0.98165272  0.60108776]]
