In [45]:
print a.shape[-1]

2


In [46]:
num_layers = 5
bn_params = [{'mode': 'train'} for i in xrange(num_layers - 1)]

In [47]:
print bn_params

[{'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}]


In [54]:
for idx in xrange(num_layers):
    print "idx = ", idx
    i_params = idx + 1
    w_str = "W%s" % (i_params)
    print w_str
    

idx =  0
W1
idx =  1
W2
idx =  2
W3
idx =  3
W4
idx =  4
W5


In [56]:
D={0:(2,3,1),1:(4,5,3),2:(9,8,7)}
for i in D:
    print D[i][2]

1
3
7


In [60]:
x = np.random.randn(3,4)
print x

[[ 1.2135928  -0.10460609 -0.18896185  0.99465212]
 [-1.40844735  0.03169156  1.32820377  1.05801736]
 [-0.02834166  0.30312793  0.08733618  0.38663994]]


In [61]:
xtemp = np.reshape(x,(x.shape[0],-1))
xtemp.shape

(3, 4)

In [69]:
a = [2, 3, 4]
len(a)

3

In [73]:
for i in xrange(6,2,-1):
    print i

6
5
4
3


In [74]:
a[:3]

[2, 3, 4]