In [16]:
import numpy as np
x = np.arange(10)
print x


[0 1 2 3 4 5 6 7 8 9]


In [17]:
print x.shape
x[2:5]


(10,)


array([2, 3, 4])

In [18]:
x[:-7]

array([0, 1, 2])

In [19]:
x[1:7:2]

array([1, 3, 5])

In [20]:
z = np.zeros((5))

In [22]:
z2 = np.zeros(5)
print z, z.shape
print z2, z2.shape

[ 0.  0.  0.  0.  0.] (5,)
[ 0.  0.  0.  0.  0.] (5,)
