In [188]:
import numpy as np
from random import randrange
a=np.arange(16).reshape(8,2)
b=np.ones((8,1))
c = np.hstack((a,b))

In [189]:
d = np.hstack([a, b])

In [193]:
x = -1*np.log(0.1)
print x
y = -1*np.log(1) + np.log(10)
print y

2.30258509299
2.30258509299


In [194]:
np.log(1)

0.0

In [203]:
z=np.arange(10)
print z, z.shape
q=np.reshape(np.arange(10),(10,1))
print q, q.shape

[0 1 2 3 4 5 6 7 8 9] (10,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] (10, 1)


In [204]:
ab = z + 3
print ab

[ 3  4  5  6  7  8  9 10 11 12]


In [205]:
ab = q + z
print ab, ab.shape

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]] (10, 10)


In [207]:
print a, a.shape

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]] (8, 2)


In [209]:
qq = np.zeros(a.shape)
print qq, qq.shape

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]] (8, 2)


In [210]:
qq = a
print qq, qq.shape

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]] (8, 2)
